schedule = [
	{
		"date": "8/29",
		"topic": "Introduction",
		"pdf": "01-intro.pdf",
		"tex": "",
		"comments": ""
	},
	{
		"date": "8/31",
		"topic": "Safety &amp; logic",
		"pdf": "02-prop.pdf",
		"tex": "02-prop.tex",
		"comments": "<a href=\"lectures/02-safety-intro.pdf\">[slides]</a>"
	},
	{
		"date": "9/5",
		"topic": "Proof",
		"pdf": "02-prop.pdf",
		"tex": "02-prop.tex",
		"comments": "",
	},
	{
		"date": "9/7",
		"topic": "Programs &amp; semantics",
		"pdf": "03-safety.pdf",
		"tex": "03-safety.tex",
		"comments": "",
	},
	{
		"date": "9/12",
		"topic": "Dynamic logic",
		"pdf": "04-safetyproofs.pdf",
		"tex": "04-safetyproofs.tex",
		"comments": "",
	},
	{
		"date": "9/14",
		"topic": "Compositional safety",
		"pdf": "04-safetyproofs.pdf",
		"tex": "04-safetyproofs.tex",
		"comments": "",
	},
	{
		"date": "9/19",
		"topic": "Memory safety",
		"pdf": "05-memsandbox.pdf",
		"tex": "05-memsandbox.tex",
		"comments": "",
	},
	{
		"date": "9/21",
		"topic": "Software fault isolation",
		"pdf": "06-sfi.pdf",
		"tex": "06-sfi.tex",
		"comments": "",
	},
	{
		"date": "9/26",
		"topic": "Soundness of inlined enforcement",
		"pdf": "06-sfi.pdf",
		"tex": "06-sfi.tex",
		"comments": "",
	},
	{
		"date": "9/28",
		"topic": "Lab 1: Intro &amp; demo",
		"pdf": "",
		"tex": "",
		"comments": "See <a href=\"https://github.com/15316-cmu/lab1-2023\">lab handout</a>. <a href=\"lectures/07-lab1-live.ipynb\">[notebook]</a> <a href=\"lectures/07-lab1-live.html\">[html]</a>",
	},
	{
		"date": "10/3",
		"topic": "Security automata",
		"pdf": "08-automata.pdf",
		"tex": "08-automata.tex",
		"comments": "", 
	},
	{
		"date": "10/5",
		"topic": "Enforcing any safety property",
		"pdf": "08-automata.pdf",
		"tex": "08-automata.tex",
		"comments": "",
	},
	{
		"date": "10/10",
		"topic": "End-to-end safety analysis",
		"pdf": "",
		"tex": "",
		"comments": "See presentation in Piazza resources.",
	},
	{
		"date": "10/12",
		"topic": "Lab 1: Office hours",
		"pdf": "",
		"tex": "",
		"comments": "Attendance optional",
	},
	{
		"date": "10/17",
		"topic": "Fall break",
		"pdf": "",
		"tex": "",
		"comments": "",
		"color": "success"
	},
	{
		"date": "10/19",
		"topic": "Fall break",
		"pdf": "",
		"tex": "",
		"comments": "",
		"color": "success"
	},
	{
		"date": "10/24",
		"topic": "Authorization, logically",
		"pdf": "09-auth.pdf",
		"tex": "09-auth.tex",
		"comments": "",
	},
	{
		"date": "10/26",
		"topic": "Bootstrapping trust",
		"pdf": "10-pki.pdf",
		"tex": "10-pki.tex",
		"comments": "",
	},
	{
		"date": "10/31",
		"topic": "Trusted computing",
		"pdf": "11-tc.pdf",
		"tex": "11-tc.tex",
		"comments": "",
	},
	{
		"date": "11/2",
		"topic": "Lab 2: Intro &amp; demo",
		"pdf": "",
		"tex": "",
		"comments": "See lab handout, starter code",
	},
	{
		"date": "11/7",
		"topic": "Democracy day",
		"pdf": "",
		"tex": "",
		"comments": "",
		"color": "success"
	},
	{
		"date": "11/9",
		"topic": "Information Flow",
		"pdf": "12-infoflow.pdf",
		"tex": "12-infoflow.tex",
		"comments": "Slides available on Canvas",
	},
	{
		"date": "11/14",
		"topic": "Security types",
		"pdf": "13-flowtypes.pdf",
		"tex": "13-flowtypes.tex",
		"comments": "",
	},
	{
		"date": "11/16",
		"topic": "Simple Security, Confinement, &amp; Soundness",
		"pdf": "",
		"tex": "",
		"comments": "",
	},	
	{
		"date": "11/21",
		"topic": "Lab 2: Office hours",
		"pdf": "",
		"tex": "",
		"comments": "Attendance optional",
	},
	{
		"date": "11/23",
		"topic": "Thanksgiving break",
		"pdf": "",
		"tex": "",
		"comments": "",
		"color": "success"
	},
	{
		"date": "11/28",
		"topic": "Defining privacy",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "11/30",
		"topic": "Provable privacy",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "12/5",
		"topic": "Privacy vulnerabilities",
		"pdf": "",
		"tex": "",
		"comments": "Not covered on final exam",
	},
	{
		"date": "12/7",
		"topic": "Final exam review",
		"pdf": "",
		"tex": "",
		"comments": "",
	}

]