schedule = [
	{
		"date": "8/29",
		"topic": "Introduction",
		"pdf": "01-intro.pdf",
		"tex": "",
		"comments": ""
	},
	{
		"date": "8/31",
		"topic": "Safety &amp; logic",
		"pdf": "02-prop.pdf",
		"tex": "",
		"comments": "<a href=\"lectures/02-safety-intro.pdf\">[slides]</a>"
	},
	{
		"date": "9/5",
		"topic": "Proof",
		"pdf": "02-prop.pdf",
		"tex": "",
		"comments": "",
	},
	{
		"date": "9/7",
		"topic": "Programs &amp; semantics",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "9/12",
		"topic": "Proving safety compositionally",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "9/14",
		"topic": "Dealing with repetition",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "9/19",
		"topic": "Memory safety",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "9/21",
		"topic": "Software fault isolation",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "9/26",
		"topic": "Lab 1: Intro &amp; demo",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "9/28",
		"topic": "Security automata",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "10/3",
		"topic": "Inline reference monitoring",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "10/5",
		"topic": "Control flow integrity",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "10/10",
		"topic": "End-to-end safety analysis",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "10/12",
		"topic": "Lab 1: Office hours",
		"pdf": "",
		"tex": "",
		"comments": "Attendance optional",
	},
	{
		"date": "10/17",
		"topic": "Fall break",
		"pdf": "",
		"tex": "",
		"comments": "",
		"color": "success"
	},
	{
		"date": "10/19",
		"topic": "Fall break",
		"pdf": "",
		"tex": "",
		"comments": "",
		"color": "success"
	},
	{
		"date": "10/24",
		"topic": "Authorization, logically",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "10/26",
		"topic": "Making authorization work",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "10/31",
		"topic": "Bootstrapping trust",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "11/2",
		"topic": "Lab 2: Intro &amp; demo",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "11/7",
		"topic": "Democracy day",
		"pdf": "",
		"tex": "",
		"comments": "",
		"color": "success"
	},
	{
		"date": "11/9",
		"topic": "Information Flow",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "11/14",
		"topic": "Security types",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "11/16",
		"topic": "Simple Security, Confinement, &amp; Soundness",
		"pdf": "",
		"tex": "",
		"comments": "",
	},	
	{
		"date": "11/21",
		"topic": "Lab 2: Office hours",
		"pdf": "",
		"tex": "",
		"comments": "Attendance optional",
	},
	{
		"date": "11/23",
		"topic": "Thanksgiving break",
		"pdf": "",
		"tex": "",
		"comments": "",
		"color": "success"
	},
	{
		"date": "11/28",
		"topic": "Defining privacy",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "11/30",
		"topic": "Provable privacy",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "12/5",
		"topic": "Privacy vulnerabilities",
		"pdf": "",
		"tex": "",
		"comments": "Not covered on final exam",
	},
	{
		"date": "12/7",
		"topic": "Final exam review",
		"pdf": "",
		"tex": "",
		"comments": "",
	}

]