schedule = [
	{
		"date": "Tue 01/13",
		"topic": "Introduction",
		"pdf": "",
		"tex": "",
		"comments": "(slides only)",
	},
	{
		"date": "Thu 01/15",
		"topic": "Propositional Logic and Proof",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Tue 01/20",
		"topic": "Dynamic Logic",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Thu 01/22",
		"topic": "Semantics of Programs",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Tue 01/27",
		"topic": "Proving Safety",
		"pdf": "",
		"tex": "",
		"comments": "Asst 1 due",
	},
	{
		"date": "Thu 01/29",
		"topic": "Memory Safety",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Tue 02/03",
		"topic": "Generating Verification Conditions",
		"pdf": "",
		"tex": "",
		"comments": "Asst 2 due",
	},
	{
		"date": "Thu 02/05",
		"topic": "Symbolic Evaluation",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Tue 02/10",
		"topic": "Program Analysis",
		"pdf": "",
		"tex": "",
		"comments": "Asst 3 due",
	},
	{
		"date": "Thu 02/12",
		"topic": "Security Automata",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Tue 02/17",
		"topic": "Inline Reference Monitors",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Thu 02/19",
		"topic": "Beyond Safety Properties",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Tue 02/24",
		"topic": "Information Flow",
		"pdf": "",
		"tex": "",
		"comments": "Lab 1 due",
	},
	{
		"date": "Thu 02/26",
		"topic": "Declassification",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Tue 03/03",
		"topic": "Spring Break",
		"pdf": "",
		"tex": "",
		"comments": "",
		"color": "success",
	},
	{
		"date": "Thu 03/05",
		"topic": "Spring Break",
		"pdf": "",
		"tex": "",
		"comments": "",
		"color": "success",
	},
	{
		"date": "Tue 03/10",
		"topic": "Termination-Sensitive Noninterference",
		"pdf": "",
		"tex": "",
		"comments": "Asst 4 due",
	},
	{
		"date": "Thu 03/12",
		"topic": "Timing Attacks",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Tue 03/17",
		"topic": "Authorization Logic",
		"pdf": "",
		"tex": "",
		"comments": "Asst 5 due",
	},
	{
		"date": "Thu 03/19",
		"topic": "Proof Search in Authorization Logic",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Tue 03/24",
		"topic": "Proof Representation",
		"pdf": "",
		"tex": "",
		"comments": "Asst 6 due",
	},
	{
		"date": "Thu 03/26",
		"topic": "Bootstrapping Trust",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Tue 03/31",
		"topic": "Lab 3 Preview",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Thu 04/02",
		"topic": "Functional and Higher-Order Information Flow",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Tue 04/07",
		"topic": "Project Day",
		"pdf": "",
		"tex": "",
		"comments": "Lab 2 due",
	},
	{
		"date": "Thu 04/09",
		"topic": "Spring Carnival",
		"pdf": "",
		"tex": "",
		"comments": "",
		"color": "success",
	},
	{
		"date": "Tue 04/14",
		"topic": "Intermittent Computing",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Thu 04/16",
		"topic": "Differential Privacy",
		"pdf": "",
		"tex": "",
		"comments": "",
	},
	{
		"date": "Tue 04/21",
		"topic": "Privacy Vulnerabilities",
		"pdf": "",
		"tex": "",
		"comments": "Not covered on final exam",
	},
	{
		"date": "Thu 04/23",
		"topic": "Final Review",
		"pdf": "",
		"tex": "",
		"comments": "Lab 3 due",
	}
]
