schedule = [
  {
    date: "Tue 01/13",
    topic: "Introduction",
    pdf: "01-intro.pdf",
    tex: "",
    comments: "(slides only)",
  },
  {
    date: "Thu 01/15",
    topic: "Safety and Semantics",
    pdf: "02-semantics.pdf",
    tex: "02-semantics.tex",
    comments: "",
  },
  {
    date: "Tue 01/20",
    topic: "Formal Proof",
    pdf: "03-proof.pdf",
    tex: "03-proof.tex",
    comments: "",
  },
  {
    date: "Thu 01/22",
    topic: "Dynamic Logic",
    pdf: "04-dynamic.pdf",
    tex: "04-dynamic.tex",
    comments: "",
  },
  {
    date: "Tue 01/27",
    topic: "Proving Safety",
    pdf: "05-safety.pdf",
    tex: "05-safety.tex",
    comments: "Asst 1 due",
  },
  {
    date: "Thu 01/29",
    topic: "Memory Safety",
    pdf: "06-memsafety.pdf",
    tex: "06-memsafety.tex",
    comments: "",
  },
  {
    date: "Tue 02/03",
    topic: "Generating Verification Conditions",
    pdf: "07-vcgen.pdf",
    tex: "07-vcgen.tex",
    comments: "Asst 2 due",
  },
  {
    date: "Thu 02/05",
    topic: "Symbolic Evaluation",
    pdf: "08-symbolic.pdf",
    tex: "08-symbolic.tex",
    comments: "",
  },
  {
    date: "Tue 02/10",
    topic: "Safety Analysis",
    pdf: "09-analysis.pdf",
    tex: "09-analysis.tex",
    comments: "Asst 3 due",
  },
  {
    date: "Thu 02/12",
    topic: "Security Automata",
    pdf: "10-automata.pdf",
    tex: "10-automata.tex",
    comments: "",
  },
  {
    date: "Tue 02/17",
    topic: "Beyond Safety Properties",
    pdf: "11-beyondsafety.pdf",
    tex: "11-beyondsafety.tex",
    comments: "",
  },
  {
    date: "Thu 02/19",
    topic: "Information Flow",
    pdf: "12-infoflow.pdf",
    tex: "12-infoflow.tex",
    comments: "",
  },
  {
    date: "Tue 02/24",
    topic: "Declassification",
    pdf: "13-declassification.pdf",
    tex: "13-declassification.tex",
    comments: "Lab 1 due",
  },
  {
    date: "Thu 02/26",
    topic: "No class",
    pdf: "",
    tex: "",
    comments: "",
    color: "success",
  },
  {
    date: "Tue 03/03",
    topic: "Spring Break",
    pdf: "",
    tex: "",
    comments: "",
    color: "success",
  },
  {
    date: "Thu 03/05",
    topic: "Spring Break",
    pdf: "",
    tex: "",
    comments: "",
    color: "success",
  },
  {
    date: "Tue 03/10",
    topic: "Termination-Sensitive Noninterference",
    pdf: "14-termination.pdf",
    tex: "14-termination.tex",
    comments: "",
  },
  {
    date: "Thu 03/12",
    topic: "Timing Attacks",
    pdf: "15-timing.pdf",
    tex: "15-timing.tex",
    comments: "",
  },
  {
    date: "Tue 03/17",
    topic: "Authorization Logic",
    pdf: "16-authlogic.pdf",
    tex: "16-authlogic.tex",
    comments: "Asst 4 due",
  },
  {
    date: "Thu 03/19",
    topic: "Proof Search in Authorization Logic",
    pdf: "17-proofsearch.pdf",
    tex: "17-proofsearch.tex",
    comments: "",
  },
  {
    date: "Tue 03/24",
    topic: "No lecture",
    pdf: "",
    tex: "",
    comments: "Asst 5 due",
    color: "success",
  },
  {
    date: "Thu 03/26",
    topic: "Proof Representation",
    pdf: "18-proofrep.pdf",
    tex: "18-proofrep.tex",
    comments: "",
  },
  {
    date: "Tue 03/31",
    topic: "Bootstrapping Trust",
    pdf: "19-trust.pdf",
    tex: "19-trust.tex",
    comments: "",
  },
  {
    date: "Thu 04/02",
    topic: "Trusted Computing",
    pdf: "20-tc.pdf",
    tex: "20-tc.tex",
    comments: "",
  },
  {
    date: "Tue 04/07",
    topic: "Lab 3 Preview",
    pdf: "",
    tex: "",
    comments: "Lab 2 due",
  },
  {
    date: "Thu 04/09",
    topic: "Spring Carnival",
    pdf: "",
    tex: "",
    comments: "",
    color: "success",
  },
  {
    date: "Tue 04/14",
    topic: "Verifiable Computing",
    pdf: "",
    tex: "",
    comments: "",
  },
  {
    date: "Thu 04/16",
    topic: "Differential Privacy",
    pdf: "22-diffprivacy.pdf",
    tex: "22-diffprivacy.tex",
    comments: "",
  },
  {
    date: "Tue 04/21",
    topic: "Mechanisms and Composition",
    pdf: "23-dpmechanisms.pdf",
    tex: "23-dpmechanisms.tex",
    comments: "",
  },
  {
    date: "Thu 04/23",
    topic: "Final Review",
    pdf: "",
    tex: "",
    comments: "Lab 3 due",
  },
];
