schedule = [
    {
	"date": "Tue 08/27",
	"topic": "Introduction",
	"pdf": "01-intro.pdf",
	"tex": "",
	"comments": "(slides only)",
    },
    {
	"date": "Thu 08/29",
	"topic": "Propositional Logic and Proof",
	"pdf": "02-prop.pdf",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 09/03",
	"topic": "Dynamic Logic",
	"pdf": "03-dynamiclogic.pdf",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Thu 09/05",
	"topic": "Semantics of Programs",
	"pdf": "04-semantics.pdf",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 09/10",
	"topic": "Proving Safety",
	"pdf": "05-safety.pdf",
	"tex": "",
	"comments": "Asst 1 due",
    },
    {
	"date": "Thu 09/12",
	"topic": "Memory Safety",
	"pdf": "06-memsafety.pdf",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 09/17",
	"topic": "Generating Verification Conditions",
	"pdf": "07-vcgen.pdf",
	"tex": "",
	"comments": "Asst 2 due",
    },
    {
	"date": "Thu 09/19",
	"topic": "Symbolic Evaluation",
	"pdf": "08-symeval.pdf",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 09/24",
	"topic": "Program Analysis",
	"pdf": "09-analysis.pdf",
	"tex": "",
	"comments": "Asst 3 due",
    },
    {
	"date": "Thu 09/26",
	"topic": "Beyond Safety Properties",
	"pdf": "10-beyondsafety.pdf",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 10/01",
	"topic": "Information Flow",
	"pdf": "11-infoflow.pdf",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Thu 10/03",
	"topic": "Declassification",
	"pdf": "12-declassification.pdf",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 10/08",
	"topic": "Midterm Review (<a href=\"solutions/pracmidterm.pdf\">practice midterm</a>)",
	"pdf": "../solutions/pracmidterm-solutions.pdf",
	"tex": "",
	"comments": "Lab 1 due",
    },
    {
	"date": "Thu 10/10",
	"topic": "Midterm Exam (<a href=\"solutions/midterm.pdf\">midterm</a>)",
	"pdf": "../solutions/midterm-solutions.pdf",
	"tex": "",
	"comments": "",
        "color": "danger",
    },
    {
	"date": "Tue 10/15",
	"topic": "Fall Break",
	"pdf": "",
	"tex": "",
	"comments": "",
        "color": "success",
    },
    {
	"date": "Thu 10/17",
	"topic": "Fall Break",
	"pdf": "",
	"tex": "",
	"comments": "",
        "color": "success",
    },
    {
	"date": "Tue 10/22",
	"topic": "Termination-Sensitive Noninterference",
	"pdf": "13-termination.pdf",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Thu 10/24",
	"topic": "Timing Attacks",
	"pdf": "14-timing.pdf",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 10/29",
	"topic": "Authorization Logic",
	"pdf": "15-authlogic.pdf",
	"tex": "",
	"comments": "Asst 4 due",
    },
    {
	"date": "Thu 10/31",
	"topic": "Proof Search in Authorization Logic",
	"pdf": "16-proofsearch.pdf",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 11/05",
	"topic": "Democracy Day (no lecture)",
	"pdf": "",
	"tex": "",
	"comments": "",
        "color": "success",
    },
    {
	"date": "Thu 11/07",
	"topic": "Proof Representation",
	"pdf": "17-proofrep.pdf",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 11/12",
	"topic": "<em>Cancelled</em>",
	"pdf": "",
	"tex": "",
	"comments": "Lab 2 due",
    },
    {
	"date": "Thu 11/14",
	"topic": "Bootstrapping Trust",
	"pdf": "18-pki.pdf",
	"tex": "",
	"comments": "(<a href=\"lectures/18-pki-slides.pdf\">slides</a>)",
    },
    {
	"date": "Tue 11/19",
	"topic": "Lab 3 Preview",
	"pdf": "",
	"tex": "",
	"comments": "Asst 5 due",
    },
    {
	"date": "Thu 11/21",
	"topic": "Functional and Higher-Order Information Flow",
	"pdf": "20-functional.pdf",
	"tex": "",
	"comments": "(by Hemant Gouni)",
    },
    {
	"date": "Tue 11/26",
	"topic": "Project Day",
	"pdf": "",
	"tex": "",
	"comments": "(no lecture)",
    },
    {
	"date": "Thu 11/28",
	"topic": "Thanksgiving",
	"pdf": "",
	"tex": "",
	"comments": "",
        "color": "success",
    },
    {
	"date": "Tue 12/03",
	"topic": "Intermittent Computing",
	"pdf": "21-intermittent.pdf",
	"tex": "",
	"comments": "(by Myra Dotzel)",
    },
    {
	"date": "Thu 12/05",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "Lab 3 due",
    },
    
]
