schedule = [
    {
	"date": "Tue 08/27",
	"topic": "Introduction",
	"pdf": "01-intro.pdf",
	"tex": "",
	"comments": "(slides only)",
    },
    {
	"date": "Thu 08/29",
	"topic": "Propositional Logic and Proof",
	"pdf": "02-prop.pdf",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 09/03",
	"topic": "Dynamic Logic",
	"pdf": "03-dynamiclogic.pdf",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Thu 09/05",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 09/10",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "Asst 1 due",
    },
    {
	"date": "Thu 09/12",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 09/17",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "Asst 2 due",
    },
    {
	"date": "Thu 09/19",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 09/24",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "Asst 3 due",
    },
    {
	"date": "Thu 09/26",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 10/01",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Thu 10/03",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 10/08",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "Lab 1 due",
    },
    {
	"date": "Thu 10/10",
	"topic": "Midterm Exam",
	"pdf": "",
	"tex": "",
	"comments": "",
        "color": "danger",
    },
    {
	"date": "Tue 10/15",
	"topic": "Fall Break",
	"pdf": "",
	"tex": "",
	"comments": "",
        "color": "success",
    },
    {
	"date": "Thu 10/17",
	"topic": "Fall Break",
	"pdf": "",
	"tex": "",
	"comments": "",
        "color": "success",
    },
    {
	"date": "Tue 10/22",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Thu 10/24",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 10/29",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "Asst 4 due",
    },
    {
	"date": "Thu 10/31",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 11/05",
	"topic": "Democracy Day",
	"pdf": "",
	"tex": "",
	"comments": "",
        "color": "success",
    },
    {
	"date": "Thu 11/07",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 11/12",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "Lab 2 due",
    },
    {
	"date": "Thu 11/14",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 11/19",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "Asst 5 due",
    },
    {
	"date": "Thu 11/21",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Tue 11/26",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Thu 11/28",
	"topic": "Thanksgiving",
	"pdf": "",
	"tex": "",
	"comments": "",
        "color": "success",
    },
    {
	"date": "Tue 12/03",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "",
    },
    {
	"date": "Thu 12/05",
	"topic": "",
	"pdf": "",
	"tex": "",
	"comments": "Lab 3 due",
    },
    
]
